name: saito
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.0+0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  fl_chart: ^0.66.0
  flutter_animate: ^4.5.0
  percent_indicator: ^4.2.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.19.0
  audioplayers: ^6.1.0
  material_symbols_icons: ^4.2709.0
  local_auth: ^2.3.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
